### PR TITLE
Establish core  Model-View-Controller

### LINKED ISSUE #10: [TO-DO]  improve separation of concerns
* refactor model to include only data member and data access, mutating action or action that combines multiple model elements should all be moved to controller
* start creation and implementation of the "page of code" schema 
* rewrite the code-gen to *actually* read the model to generate the code

### PR DESCRIPTION
**Pull request by spiritanand**
Partially fixes #10 

Change DB from SQLite to JSON (using the node's file system `fs`)

### CODE REVIEW

**Comment by spiritanand** [comment]
@Sing-Li I have implemented `loadSummarizationChain` end to end. We can now generate code based on its block parameters.

**Comment by Sing-Li** [comment]
This is awesome work @spiritanand !  Thanks.  I'll test it and then merge.    Hope to see you in our meeting this week.

The next thing to look at is adding project load and save capabilities.  https://github.com/llmshare/llmproto/issues/15

**Comment by Sing-Li** [comment]
@spiritanand  please implement ALL the parameters of each block and also use a rete  socket link to link the related blocks

Right now, the blocks are just acting as input field (like a form) which defeats the goal of the project.

Also, the blocks should not be static,   please make sure the initial page is blank.

A drop down menu should allow the selection of the block.

Also -- as per prior discussion (scroll up) --  we don't want the generate code box.  Code should be generated to a file via a top-nav or menu item.   (please re-read our earlier discussion)

**Comment by spiritanand** [comment]
@Sing-Li even if I connect each block it would be just for aesthetics. The actual values would still be controlled by the other floating inputs and not feeding into the main chain block.

**Comment by Sing-Li** [comment]
@spiritanand  NOT if each block is not static.  And that the end user can use a drop down list to create it.  Then they can select different blocks to create and link.

We're not building a form fill code gen webapp.   But a drag and drop code creator.

**Comment by Sing-Li** [comment]
The fact that the specific case you are doing right now is static (because we scoped it that way to make it easier for you)  shouldn't confuse the bigger picture.

**Comment by spiritanand** [comment]
@Sing-Li If we are looking at actually flowing different data from different blocks into the main block then I believe we will have to change our approach.

**Comment by Sing-Li** [comment]
@spiritanand  please reread the discussion we had CAREFULLY - it was before you went on the "choose DB detour"  --> https://github.com/llmshare/llmproto/issues/10#issuecomment-1712520286

**Comment by Sing-Li** [comment]
Yes, your schema *has* to reflect this more general approach.

**Comment by spiritanand** [comment]
@Sing-Li it would be better if we could get on a call.

**Comment by Sing-Li** [comment]
ok ... talk to you in the channels.

**Comment by Sing-Li** [comment]
Just edited title to better fit the work.  Thanks.

**Comment by spiritanand** [comment]
> Also -- as per prior discussion (scroll up) -- we don't want the generate code box. Code should be generated to a file via a top-nav or menu item. (please re-read our earlier discussion)

That is true @Sing-Li, I remember that very well. I just feel it is a better DX for us to see the result of what our nodes are able to generate right next to the generate button.

**Comment by Sing-Li** [comment]
Please add the save-to-file code and then make the "generated code viewer" optional, default not-visible.   Then it will satisfy both of us.

In fact - the drop down menu can have an option ....   **show generated code**  that toggles and default to    *hide generated code*

**Comment by spiritanand** [comment]
> Please add the save-to-file code and then make the "generated code viewer" optional, default not-visible. Then it will satisfy both of us.
> 
> In fact - the drop down menu can have an option .... **show generated code** that toggles and default to _hide generated code_

is this something we want to tackle in this PR?

**Comment by Sing-Li** [comment]
Yes, it is.   We shouldn't leave the code generation box around, taking up the screen real estate.

**Comment by spiritanand** [comment]
> Yes, it is. We shouldn't leave the code generation box around, taking up the screen real estate.

Cool. I will do that. I was just thinking it is better to stick with this view till more people start to use the app. Easier for devs to see changes and contribute.

**Comment by spiritanand** [comment]
@Sing-Li I am done with all the functional aspects. Please LMK if anything else is needed?

right click to add nodes
image

sockets to connect the node to the chain
image

**Comment by Sing-Li** [comment]
@spiritanand   the add node box has an edit field that is useless at the top, can you please remove it.

Please move the Generate Code to a menu at the top (use react top nav)   and remove the generate code dialog.  It is hogging up space on the screen for no good purpose.   Save it to a `.pro` file.  We *need* the file save before others can pick this up and work on it.

The OpenAI block has 2 arguments.  Why is only one implemented?      

Please remove those "input" and "output" labels and make sure the Langchain field names are the actual labels, otherwise there is no way to generate appropriate code.   The field names must be stored in the schema!

Also we agreed that nothing should connect to the Chain block earlier.     

Thanks.

**Comment by spiritanand** [comment]
> @spiritanand the add node box has an edit field that is useless at the top, can you please remove it.

@Sing-Li which box are you talking about? I can only see a search bar when adding.


> Please move the Generate Code to a menu at the top (use react top nav) and remove the generate code dialog. It is hogging up space on the screen for no good purpose. Save it to a `.pro` file. We _need_ the file save before others can pick this up and work on it.

We are already saving every project in a JSON file. It is updated in real-time.


> The OpenAI block has 2 arguments. Why is only one implemented?

@Sing-Li could you please help me with the doc for this? I saw there are way more than 2 arguments in OpenAI.

> Please remove those "input" and "output" labels and make sure the Langchain field names are the actual labels, otherwise there is no way to generate appropriate code. The field names must be stored in the schema!

Sure, I will remove the labels, but they are only labels here and are not impacting the actual result of the code (yet).

> Also we agreed that nothing should connect to the Chain block earlier.

I am unable to understand. Does this mean that there should be no input socket in the chain?

**Comment by Sing-Li** [comment]
@spiritanand 

> > @spiritanand the add node box has an edit field that is useless at the top, can you please remove it.
> 
> @Sing-Li which box are you talking about? I can only see a search bar when adding.

Delete the search bar.

> 
> > Please move the Generate Code to a menu at the top (use react top nav) and remove the generate code dialog. It is hogging up space on the screen for no good purpose. Save it to a `.pro` file. We _need_ the file save before others can pick this up and work on it.
> 
> We are already saving every project in a JSON file. It is updated in real-time.
> 

Remove the code generation box by default.   We want to use the entire screen to assemble our program!  Add a menu at the top of the window to optionally make the code gen box visible if you want.

> > The OpenAI block has 2 arguments. Why is only one implemented?
> 
> @Sing-Li could you please help me with the doc for this? I saw there are way more than 2 arguments in OpenAI.
> 

You're correct.  Let's get as many of them in the schema as possible (the most frequently used ones).s

> > Please remove those "input" and "output" labels and make sure the Langchain field names are the actual labels, otherwise there is no way to generate appropriate code. The field names must be stored in the schema!
> 
> Sure, I will remove the labels, but they are only labels here and are not impacting the actual result of the code (yet).
> 

Doesn't matter, they serve absolutely no purpose and are leftover from the sample program.   Use the space for actual block arguments.

> > Also we agreed that nothing should connect to the Chain block earlier.
> 
> I am unable to understand. Does this mean that there should be no input socket in the chain?

Exactly.   We discussed at length previously.  The socket/link should REALLY be at each argument/parameter but you said you didn't want to code it at this time.   So we need to bring it to the side of the block.  NOTHING should connect to the Chain block.

Thanks.

**Comment by spiritanand** [comment]
> Delete the search bar.

@Sing-Li the context menu is not that configurable. I am not sure if the search bar can be removed trivially.



> Remove the code generation box by default. We want to use the entire screen to assemble our program! Add a menu at the top of the window to optionally make the code gen box visible if you want.

Done.


> You're correct. Let's get as many of them in the schema as possible (the most frequently used ones).s

@Sing-Li there are way too many of them. If you could suggest one or two parameters I would be happy to add them, however adding all is just a repetitive task and can be done as required.



> Doesn't matter, they serve absolutely no purpose and are leftover from the sample program. Use the space for actual block arguments.

The idea I was trying to implement was that each block will forward an object to the other block. This way, we would not need multiple output sockets in blocks which have multiple parameters (which will be most blocks).

> So we need to bring it to the side of the block. NOTHING should connect to the Chain block.

I am having a hard time recalling what we had discussed. I have already implemented what we had discussed. There are outgoing sockets from the prerequisite nodes to the main chain node, which has an input socket.

**Comment by Sing-Li** [comment]
> > Delete the search bar.
> 
> @Sing-Li the context menu is not that configurable. I am not sure if the search bar can be removed trivially.
> 

Please take a deep look.  There must be some way of making it look the way we want  (via CSS?) 

> > Remove the code generation box by default. We want to use the entire screen to assemble our program! Add a menu at the top of the window to optionally make the code gen box visible if you want.
> 
> Done.

@spiritanand  did you commit your code?

> 
> > You're correct. Let's get as many of them in the schema as possible (the most frequently used ones).s
> 
> @Sing-Li there are way too many of them. If you could suggest one or two parameters I would be happy to add them, however adding all is just a repetitive task and can be done as required.
> 

Let's do about 3 --- BUT get their *label name* onto the block.  Take a look at your block - right now it just has the entry field.  And a meaningless  "output" leftover.  It should have  "temp:  Temperature"  as the label.  Without this information you can't generate the proper custom code.

image


> > Doesn't matter, they serve absolutely no purpose and are leftover from the sample program. Use the space for actual block arguments.
> 
> The idea I was trying to implement was that each block will forward an object to the other block. This way, we would not need multiple output sockets in blocks which have multiple parameters (which will be most blocks).
> 
> > So we need to bring it to the side of the block. NOTHING should connect to the Chain block.
> 
> I am having a hard time recalling what we had discussed. I have already implemented what we had discussed. There are outgoing sockets from the prerequisite nodes to the main chain node, which has an input socket.

IT is the words "OUTPUT" and "INPUT" that you need to remove.    And making sure the Chain block has no connection possible.

Thanks.

**Comment by spiritanand** [comment]
> Please take a deep look. There must be some way of making it look the way we want (via CSS?)

Yup, I looked into it, there are a few ways to edit it, but I could not find a way that helps us create nodes and at the same time remove the search bar.



> @spiritanand did you commit your code?

Just pushed the code.


> Let's do about 3 --- BUT get their _label name_ onto the block. Take a look at your block - right now it just has the entry field. And a meaningless "output" leftover. It should have "temp: Temperature" as the label. Without this information you can't generate the proper custom code.

Alright sure. I will implement 3 parameters from OpenAI, all will be perfectly labelled :).

> IT is the words "OUTPUT" and "INPUT" that you need to remove

Alright, they will be removed.

> And making sure the Chain block has no connection possible.

Alright, the chain block will have no sockets.

**Comment by spiritanand** [comment]
Also, I guess it would be good to have the text splitter block labelled, right?

**Comment by spiritanand** [comment]
Updated view:-
image

- Labelled Inputs for LLM and text splitter
- No input socket on chain
- button to download (generate) code

@Sing-Li if this looks right, I will get started on implementing some other parameters of OpenAI.

**Comment by Sing-Li** [comment]
@spiritanand  it is a lot better.  Can we please:

1. be consistent with the labels, either on the side or on top --  for openAI block move the label to the side
2. connect the OpenAI and RecursiveCharacterTextSplitter blocks
3. allow for specifying the variable/argument names,  not just the type -- we will need to store this in our schema since it is used to generate the code

Do you know what a TopNav or Top Menu is?   We need to add that to replace the button at the top.

Yes, please add 2 more (what you think is the most frequently used) parameters to  openAI block  🙏 

Thanks.

**Comment by spiritanand** [comment]
@Sing-Li 
For 2,
```
const text = fs.readFileSync("state_of_the_union.txt", "utf8");
const model = new OpenAI({ temperature: 0 });
const textSplitter = new RecursiveCharacterTextSplitter({ chunkSize: 1000 });
const docs = await textSplitter.createDocuments([text]);

// This convenience function creates a document chain prompted to summarize a set of documents.
const chain = loadSummarizationChain(model, {
  type: "map_reduce",
  returnIntermediateSteps: true,
});
const res = await chain.call({
  input_documents: docs,
});
```

This is code we are trying to generate. Why would we need to connect the LLM to the text splitter? The LLM is fed into the chain, which then uses the text (split by the text splitter) to generate a response.

For 3,
do you mean we need to give values for holding the variables (e.g. const chain)? If not, then please explain further.



> Do you know what a TopNav or Top Menu is? We need to add that to replace the button at the top.

Yes, I am aware of a TopNav/Top Menu, how is that to be replaced with the button on the top? I could not understand? Do we want a button in the top nav to be called generate code? Also, would this be a relevant addition to this PR?

**Comment by Sing-Li** [comment]
> @Sing-Li For 2,
> 
> ```
> const text = fs.readFileSync("state_of_the_union.txt", "utf8");
> const model = new OpenAI({ temperature: 0 });
> const textSplitter = new RecursiveCharacterTextSplitter({ chunkSize: 1000 });
> const docs = await textSplitter.createDocuments([text]);
> 
> // This convenience function creates a document chain prompted to summarize a set of documents.
> const chain = loadSummarizationChain(model, {
>   type: "map_reduce",
>   returnIntermediateSteps: true,
> });
> const res = await chain.call({
>   input_documents: docs,
> });
> ```
> 
> This is code we are trying to generate. Why would we need to connect the LLM to the text splitter? The LLM is fed into the chain, which then uses the text (split by the text splitter) to generate a response.


@spiritanand  because you're being inconsistent.

`RecursiveCharacterTextSplitter`  and `OpenAI` are *types* and they are blocks. 

For some reason, you have a block called *Chain*   <-- that is a variable/const name!!!      It should be labeled with its type --  `loadSummarizationChain` !!
> 
> For 3, do you mean we need to give values for holding the variables (e.g. const chain)? If not, then please explain further.
> 

Yes, once you fix the inconsistency, then you should also provide some way to set the "name" of the variables and constants.   They *MUST* be in the schema or else we can't generate any code.

> > Do you know what a TopNav or Top Menu is? We need to add that to replace the button at the top.
> 
> Yes, I am aware of a TopNav/Top Menu, how is that to be replaced with the button on the top? I could not understand? Do we want a button in the top nav to be called generate code? Also, would this be a relevant addition to this PR?

No button in the menu.  Just a menu, similar to:

File ---> Load,  Save, Save As, Exit
Code ---> Generate

Thanks.

**Comment by spiritanand** [comment]
Sure @Sing-Li I will update the label of the chain block. However, that still begs the question, why do we need to connect the LLM to the Text Splitter?

Also, why would be need to give the user a way to store variable names? What is the benefit to the user from that?

Update: Name of chain node (block) changed to `LoadSummarizationChain`

**Comment by Sing-Li** [comment]
> Sure @Sing-Li I will update the label of the chain block. However, that still begs the question, why do we need to connect the LLM to the Text Splitter?
> 

Hmm.  OK.   Let's leave it for now. 

> Also, why would be need to give the user a way to store variable names? What is the benefit to the user from that?

We absolutely need to do that @spiritanand    This is a code generator project.   Please re-read/recall very carefully the lengthy meeting and discussion we have several weeks ago on the design.    Take a look at this 3 weeks old message - examine the schema carefully here:  https://github.com/llmshare/llmproto/issues/10#issuecomment-1712522864

User needs control of variable/const name sometimes because the generated code may be used in another context that we have no control over.   And as the chains gets more complex (not in this trivial contrived example)  this will become a much bigger problem.

@spiritanand  please add TopNav as mentioned

> 
> Update: Name of chain node (block) changed to `LoadSummarizationChain`

Thanks.

**Comment by spiritanand** [comment]
Valid point. I will add in the name of the instance as well. Shouldn't take too long. Anything else @Sing-Li ?

**Comment by Sing-Li** [comment]
> Valid point. I will add in the name of the instance as well. Shouldn't take too long. Anything else @Sing-Li ?

@spiritanand    TopNav with menu.   This should give it that "code generator app" feel, instead of the current one-shot playground feel.

I'll give it a test and merge it after.    We'll be ready for other TO DOs in the issues list.        (I'll add that socket + link subclass that we've discussed to the TO DOs)

Thanks.

**Comment by Sing-Li** [comment]
@spiritanand  one more (hopefully small) item that I noticed missing.   Please make sure other meta data such as the (x.y) position of the block, plus its settings/states are also saved in the schema.   Without them, it would be impossible to work on multiple projects.

**Pull request merged**
