### PR TITLE
Feat: Menubar

### PR DESCRIPTION
**Pull request by spiritanand**
Implemented top nav bar.

image

Blocks now contain an instance name field @Sing-Li

### CODE REVIEW

**Comment by spiritanand** [comment]
@Sing-Li I can add https://github.com/llmshare/llmproto/pull/14#issuecomment-1738998683 this, however I am not sure how we will use the values when the user continues with the current project (in a new session).

**Comment by Sing-Li** [comment]
@spiritanand it is *not just* _instance name_       Every single field / argument should have a name as well.

As far as the x, y location OF ALL blocks and their state.  It is absolutely necessary to have them.  Otherwise, users won't be able to work with multiple projects.

Please read this carefully -> https://github.com/llmshare/llmproto/pull/14#issuecomment-1738998683

I think we should also add the size of each block as well as state that is stored in with the nodes.

**Comment by Sing-Li** [comment]
The current schema is not really applicable.  We'll need to revise it according to the comment prior.  And our discussion a month ago.

Also were you unable to remove the _search bar_ on top of the drop down?   Have you researched rete.js code?  thanks.

**Comment by Sing-Li** [comment]
@spiritanand I've tested it.   The topnav is not implemented correctly.  Please re-read the prior instructions!    We should not add tons of code and dependencies just to ADD BACK the button that you've removed a few PRs ago.


Read this lengthy discussion CAREFULLY - and note the requirements of the TopNav/Menu ( where it said *NO button in the menu....*)  -->  https://github.com/llmshare/llmproto/pull/14#issuecomment-1738198630

**Comment by spiritanand** [comment]
> @spiritanand it is _not just_ _instance name_ Every single field / argument should have a name as well.

A name for every argument? I did not understand this @Sing-Li We are already storing the name of the instances the user can edit.



> As far as the x, y location OF ALL blocks and their state. It is absolutely necessary to have them. Otherwise, users won't be able to work with multiple projects.

I agree @Sing-Li it is absolutely necessary, I am just saying that I am not sure how we will use those coordinates when the user continues from an existing project. I mean, we will have to see how we can render a node at the exact coordinate.

> The current schema is not really applicable. We'll need to revise it according to the comment prior. And our discussion a month ago.

Yes, of course, revising the schema is not something which is too difficult. It can be done, but before that we need to be clear on what it needs to be.

> Also were you unable to remove the _search bar_ on top of the drop down? Have you researched rete.js code?

Yes I did, I could not find a way in my probe.



> @spiritanand I've tested it. The topnav is not implemented correctly. Please re-read the prior instructions! We should not add tons of code and dependencies just to ADD BACK the button that you've removed a few PRs ago.
> 
> Read this lengthy discussion CAREFULLY - and note the requirements of the TopNav/Menu ( where it said _NO button in the menu...._) --> [#14 (comment)](https://github.com/llmshare/llmproto/pull/14#issuecomment-1738198630)

@Sing-Li what and how should a top nav be? How exactly will the code be generated if there are no dependencies? The button needs to be replaced with what exactly?

**Comment by Sing-Li** [comment]
@spiritanand 

> > @spiritanand it is _not just_ _instance name_ Every single field / argument should have a name as well.
> 
> A name for every argument? I did not understand this @Sing-Li We are already storing the name of the instances the user can edit.
> 

OK.  Let me do it after the merge.   

> > As far as the x, y location OF ALL blocks and their state. It is absolutely necessary to have them. Otherwise, users won't be able to work with multiple projects.
> 
> I agree @Sing-Li it is absolutely necessary, I am just saying that I am not sure how we will use those coordinates when the user continues from an existing project. I mean, we will have to see how we can render a node at the exact coordinate.

Yes, add it now.  (even if you are unable to find the way to put blocks at specific position)

> 
> > The current schema is not really applicable. We'll need to revise it according to the comment prior. And our discussion a month ago.
> 
> Yes, of course, revising the schema is not something which is too difficult. It can be done, but before that we need to be clear on what it needs to be.
> 

We are clear.   Just add the co-ordinate and size.   We'll grow it as needed.  BUT we must change it - because right now it is not applicable to our app.  We NEED metadata for the blocks.

> > Also were you unable to remove the _search bar_ on top of the drop down? Have you researched rete.js code?
> 
> Yes I did, I could not find a way in my probe.
> 

Unfortunate.  We'll see if other community members can help later.   We need to remove it.


> > @spiritanand I've tested it. The topnav is not implemented correctly. Please re-read the prior instructions! We should not add tons of code and dependencies just to ADD BACK the button that you've removed a few PRs ago.
> > Read this lengthy discussion CAREFULLY - and note the requirements of the TopNav/Menu ( where it said _NO button in the menu...._) --> [#14 (comment)](https://github.com/llmshare/llmproto/pull/14#issuecomment-1738198630)
> 
> @Sing-Li what and how should a top nav be? How exactly will the code be generated if there are no dependencies? The button needs to be replaced with what exactly?

image

**Comment by spiritanand** [comment]
> @Sing-Li what and how should a top nav be? How exactly will the code be generated if there are no dependencies? The button needs to be replaced with what exactly?

@Sing-Li so there should basically be a dropdown menu with two items and multiple subitems?

**Comment by Sing-Li** [comment]
> > @Sing-Li what and how should a top nav be? How exactly will the code be generated if there are no dependencies? The button needs to be replaced with what exactly?
> 
> @Sing-Li so there should basically be a dropdown menu with two items and multiple subitems?

Yes. @spiritanand     Then @Safdarahmedd can hook his file manager into the menu subitems later.   And the entire menu will expand with many more items and subitems over time.

**Comment by spiritanand** [comment]
> and size. We'll grow it as needed. BUT we must change it - because right now it is not applicable to our app. We NEED metadata for the blocks.

For now, the size is constant and cannot be edited by the user @Sing-Li
Maybe we can add size once it is configurable.

**Comment by Sing-Li** [comment]
@spiritanand  thanks.  Looks good.  Merging this down now.

**Pull request merged**
