### PR TITLE
[Draft] File Manager

### LINKED ISSUE #15: [TO-DO]  Implement project file manager
Add  "Project"  menu:

"Load" and "Save"  and "Save As" menu items.

Enabling anyone to:

1.  Load `loadsummarizationchain1.pro`  project file  
2.  Make modifications to parameters visually via the rete view
3.  Save As `loadsummarizationchain2.pro`  project file

### PR DESCRIPTION
**Pull request by Safdarahmedd**
Working on #15

### CODE REVIEW

**Comment by Sing-Li** [comment]
@Safdarahmedd did you mention a `yarn` based PR as well?

**Comment by Safdarahmedd** [comment]
I was going to create a PR for that but it seems to have been resolved with one of @spiritanand 's commits. The .gitignore file contains ```node_modules``` directory and ```.yarn-integrity``` file, which should prevent the missing dependency issue with yarn builds.

**Comment by Sing-Li** [comment]
👌  Please try to keep this PR up-to-date (use it to save your work)  instead of an empty file.

**Comment by Sing-Li** [comment]
@Safdarahmedd any progess?

**Comment by Safdarahmedd** [comment]
@spiritanand refer `src/components/menubar/submenus/filemenu/loadfile.tsx`

My approaches so far have been:
1. Use states to save the current state as a file object and load/update/save it as needed. But states are local to component so it didn't work
2. Try passing the state between components - this would require creating parent-child relationships between components, and passing the file object through props, going all the way up to the root component. This would reduce component modularity and require changes to a lot of files.
3. Creating a global state within loadfile component, which will persist across components - but creating globals is not good practice, so did not follow that path.
4. A more promising approach seemed to access the browser's local storage directly. Although we might need to parse our file object as a string before storage. I first tried using the HTML DOM element `window.localStorage`, and then `localStorage` property of JavaScript - I am probably not parsing the file correctly or missing something with `window()`

Let me know if you can spot where I am going wrong, or if you feel there is a better way to approach this issue
Thanks!

**Comment by Safdarahmedd** [comment]
@Sing-Li there is another way to tackle this -  we could use a state management library like Redux. But I feel we should only introduce it IF we would require persistent state management for other use cases as well. If not, then manipulating browser storage is more efficient for this issue

**Comment by spiritanand** [comment]
@Safdarahmedd the approach we are following atm is to save the state of the app in a text file (with a suitable name, in a suitable subfolder) and manipulating it using the node `fs` module. This will require the use of `apis` for CRUD ing the file, since `fs` won't work on the browser✌️

So in this case, each file could be saved with a different name (using a `uuid`)

The current approach of directly updating the file in the browser needs to be replaced with an `api` flow.

LMK if anything else pops up.

**Comment by Sing-Li** [comment]
@Safdarahmedd please do let us know ASAP if the above instruction is above your level of understanding.   We really need a workable implementation of this file manager (actually not too complex) almost 3 weeks ago.    

We can assign this to someone more capable and then find you other items to contribute to.  Thanks.

**Comment by Safdarahmedd** [comment]
@Sing-Li I believe I can implement this. I just need some clarification from you and @spiritanand on a few points:

1. To save the state of the app, I should reference the `data.json` file, right? 
2. `Save` should update the most recent file (suppose `LoadSummarizationChain1.pro`), while `Save As` will NECESSARILY create a new file called `LoadSummarizationChain2.pro` or we can allow custom names?
3. `Save As` will remain disabled until the state of the app changes.
4. For file save I can simply call the `APIs` that are currently being used to save state?
5. There are folders in the `api` directory such as `chain/[id]`, `langchain/[id]` - do I need to manipulate these folder names for each instance of saving a file, or is this `[id]` not related to the `uuid` of the files?

Apart from these I have a very clear idea of what I need to do and will get to it right away 🙌🏻

**Comment by spiritanand** [comment]
> 1. To save the state of the app, I should reference the `data.json` file, right?

yes you can do that



> 2\. `Save` should update the most recent file (suppose `LoadSummarizationChain1.pro`), while `Save As` will NECESSARILY create a new file called `LoadSummarizationChain2.pro` or we can allow custom names?

> 3\. `Save As` will remain disabled until the state of the app changes.

I think instead of giving the user options to save or save as, it would be better (for now) to automatically save and update the user's work.

> 5\. There are folders in the `api` directory such as `chain/[id]`, `langchain/[id]` - do I need to manipulate these folder names for each instance of saving a file, or is this `[id]` not related to the `uuid` of the files?

this` [id]` is related to the `uuid` of the file. I have also created a function that can edit files based on the `uuid` provided (`src/db/utils.ts` -> `writeFile`), you can change it a little to make it more modular if you wish (for example adding a subfolder parameter in the function)
Similar to this, you will also need the `uuid` to manipulate the file in discussion.

**Comment by spiritanand** [comment]
> 4\. For file save I can simply call the `APIs` that are currently being used to save state?

@Safdarahmedd you can do that, but right now the app is only working on a singular data file, without any way for the user to change the working file or view all his files. This is precisely what needs to be tackled.

**Comment by Sing-Li** [comment]
@Safdarahmedd you're going about this problem in all the wrong directions.  We do not need or want to save the UI graph.  We want to save the schema (from the schema we'll always be able to regenerate the UI graph).   

Please let us know if you understand the above statement asap.

**Comment by Safdarahmedd** [comment]
@Sing-Li but I am not tackling the UI graph at all. I am thinking about saving the schema in the exact format that is currently being stored in the `data.json` file but for different files with unique IDs. It is only storing information about individual nodes and not the UI graph. The graph can easily be generated from this schema. 

Please let me know if I am misunderstanding something

**Comment by Sing-Li** [comment]
That's correct.  Exactly what we need NOW.  Why all the different
approaches then?   Let see the implementation.

**Comment by Safdarahmedd** [comment]
On it!

**Comment by Sing-Li** [comment]
Closing this as per our discussions in DM.

**Pull request closed without merging**
